### ISSUE TITLE
FAQ last session 

### ISSUE THREAD

**Issue by guilgautier** [guilgautier/sdia-python#1]
Please list here the questions, notions, problems you'd like we discuss during our last session.

**Comment by SnowHawkeye** [comment]
My question is about mistakes in git histories. [Here is an example of a bad commit I made for our lab](https://github.com/SnowHawkeye/sdia-python/commit/dc85c0a30e5013b885e766efd6b45a2c93821d80). It's meaningless and I would have liked to delete it. The only way i see is to rewrite the history with a rebase, which is very unsafe on the `main` branch. Is there a way to do it more safely, or to add a comment / tag to the commit ? How can we avoid mistakes like that in the first place?

**Comment by aurelienO** [comment]
In a few lessons, we have seen examples of Python lambda functions. Is it possible to see how to write it and some examples of use?

**Comment by guilgautier** [comment]
@SnowHawkeye https://github.com/guilgautier/sdia-python/issues/1#issuecomment-936779542
> My question is about mistakes in git histories. [...] The only way i see is to rewrite the history [...] 

Everyone makes mistakes, and it's part of one's history.
Regarding your git history, rewriting/cleaning your **local**, **unbranched** and **unpushed**  history is totally fine, and sometimes even desired (rewording commit messages, squashing commits, adding missing files to your last commit, ...).
On the contrary, when commits are shared between branches or (worse) shared with collaborators, rewriting can make histories diverge, difficult to reconcile, and overall it may impact everyone's work, badly.

> How can we avoid mistakes like that in the first place?
- discipline and experience are key I guess
- work in a separate branch to avoid potential "contamination" of the `main` branch
- use `git status`, `git diff` commands before even thinking of `git add/commit`
- use additional tools like, `black`, `pytest`, `pydocstyle` etc., to make sure everything is formatted, tested, etc.
   - you can have a look at https://pre-commit.com/ hooks, cf. the `.pre-commit-config.yaml` file

When it comes to notebooks
- avoid using notebooks and/or do not version control them (exclude them in the `.gitignore` file)
- for example [scikit-learn](https://github.com/scikit-learn/scikit-learn) doesn't use notebooks, even for showcase (in fact notebooks are generated from `.py` files, but you won't find `.ipynb` files in the repo).

--- 

I can give a few more words and/or give a quick demo about this during the last session.

**Comment by JustineBrgn** [comment]
Would it be possible to make a checklist of the steps to follow when starting a new python project (creating a new environment, new Github repository,... ) and how to organise it? 
(Sorry the message is quite late)

**Comment by louisfrm** [comment]
Could we talk about git branches?

**Comment by LoanSarazin** [comment]
Could we talk about licenses ? Which one do we have to chose and how are they all different ?
